<!DOCTYPE html>
<html lang="he" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>השוואת מחירי דיור אינטראקטיבית</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Assistant:wght@400;600;700&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Assistant', sans-serif;
        }
        .chart-container {
            position: relative;
            height: 40vh;
            width: 100%;
        }
        .tab-btn {
            transition: all 0.3s ease;
        }
        .tab-btn.active {
            background-color: #1E40AF; /* bg-blue-800 */
            color: white;
            font-weight: 700;
            box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
        }
        .price-original { color: #16A34A; /* text-green-600 */ font-weight: 600; }
        .price-new { color: #DC2626; /* text-red-600 */ font-weight: 600; }
    </style>
</head>
<body class="bg-gray-100 text-gray-800">

    <div class="container mx-auto p-4 md:p-8 max-w-7xl">
        <header class="text-center mb-8">
            <h1 class="text-3xl md:text-4xl font-bold text-blue-900">השוואת מחירי דיור</h1>
            <p class="text-lg text-gray-600 mt-2">ניתוח השוואתי בין ההסכם המקורי להצעה החדשה</p>
        </header>

        <!-- Controls -->
        <div class="flex flex-col md:flex-row justify-center gap-4 md:gap-8 mb-8">
            <!-- Location Tabs -->
            <div class="flex justify-center bg-gray-200 rounded-full p-1 shadow-inner">
                <button id="btn-location-בקעה" class="tab-btn location-btn w-full md:w-auto px-6 py-2 rounded-full text-lg" data-location="בקעה">בקעה</button>
                <button id="btn-location-שטח המחנה" class="tab-btn location-btn w-full md:w-auto px-6 py-2 rounded-full text-lg" data-location="שטח המחנה">שטח המחנה</button>
            </div>
            <!-- Age Group Tabs -->
            <div class="flex justify-center bg-gray-200 rounded-full p-1 shadow-inner">
                <button class="tab-btn age-btn px-4 py-2 rounded-full" data-age="עד גיל 30">עד גיל 30</button>
                <button class="tab-btn age-btn px-4 py-2 rounded-full" data-age="30-37">גילאי 30-37</button>
                <button class="tab-btn age-btn px-4 py-2 rounded-full" data-age="תושבים וגילאי 38 ומעלה">38+ ותושבים</button>
            </div>
        </div>

        <!-- Content Area -->
        <div class="bg-white p-4 sm:p-6 rounded-2xl shadow-lg">
            <h2 id="chart-title" class="text-2xl font-bold text-center mb-6 text-blue-800"></h2>
            
            <!-- Chart -->
            <div class="chart-container mb-8">
                <canvas id="priceChart"></canvas>
            </div>

            <!-- Table -->
            <div class="overflow-x-auto">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">סוג דירה</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">ספט' 24</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">ספט' 25</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">ספט' 26</th>
                            <th scope="col" class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">ארנונה חודשית</th>
                        </tr>
                    </thead>
                    <tbody id="price-table-body" class="bg-white divide-y divide-gray-200">
                        <!-- Rows will be injected by JS -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        // --- Data Structure ---
        // This object holds all the price data extracted from the provided files.
        const priceData = {
            'בקעה': {
                'עד גיל 30': [
                    { type: 'דמי הרשאה/דירות גן 2 חדרים', original: { '24': 1000, '25': 1000, '26': 1000 }, new: { '25': 1110, '26': 1220 }, arnona: 80 },
                    { type: 'דירות גן 3 חדרים', original: { '24': 2000, '25': 2000, '26': 2000 }, new: { '25': 1148, '26': 1296 }, arnona: 98 },
                    { type: 'קרווילה: יח\' הורים+סלון+2 חדרים', original: { '24': 2200, '25': 2200, '26': 2200 }, new: { '25': 2135, '26': 2270 }, arnona: 135 },
                    { type: 'קרווילה: יח\' הורים+סלון+חדר', original: { '24': 2600, '25': 2600, '26': 2600 }, new: { '25': 2354, '26': 2508 }, arnona: 154 },
                ],
                '30-37': [
                    { type: 'דמי הרשאה/דירות גן 2 חדרים', original: { '24': 1600, '25': 1600, '26': 1600 }, new: { '25': 1700, '26': 1800 }, arnona: 80 },
                    { type: 'דירות גן 3 חדרים', original: { '24': 2400, '25': 2400, '26': 2400 }, new: { '25': 2200, '26': 2400 }, arnona: 98 },
                    { type: 'קרווילה: יח\' הורים+סלון+2 חדרים', original: { '24': 2600, '25': 2600, '26': 2600 }, new: { '25': 2600, '26': 2800 }, arnona: 135 },
                    { type: 'קרווילה: יח\' הורים+סלון+חדר', original: { '24': 3300, '25': 3300, '26': 3300 }, new: { '25': 2800, '26': 3000 }, arnona: 154 },
                ],
                'תושבים וגילאי 38 ומעלה': [
                    { type: 'דמי הרשאה/דירות גן 2 חדרים', original: { '24': 2100, '25': 2100, '26': 2100 }, new: { '25': 2200, '26': 2300 }, arnona: 80 },
                    { type: 'דירות גן 3 חדרים', original: { '24': 3500, '25': 3500, '26': 3500 }, new: { '25': 2700, '26': 2900 }, arnona: 98 },
                    { type: 'קרווילה: יח\' הורים+סלון+2 חדרים', original: { '24': 3800, '25': 3800, '26': 3800 }, new: { '25': 3100, '26': 3300 }, arnona: 135 },
                    { type: 'קרווילה: יח\' הורים+סלון+חדר', original: { '24': 4500, '25': 4500, '26': 4500 }, new: { '25': 3400, '26': 3700 }, arnona: 154 },
                ]
            },
            'שטח המחנה': {
                'עד גיל 30': [
                    { type: 'דירת נוער/סדנה/גדולה', original: { '24': 3100, '25': 3100, '26': 3100 }, new: { '25': 3317, '26': 3534 }, arnona: 217 },
                    { type: 'דירה מורחבת/קטנה', original: { '24': 3000, '25': 3000, '26': 3000 }, new: { '25': 3186, '26': 3372 }, arnona: 286 },
                    { type: 'קרווילה מורחבת', original: { '24': 3800, '25': 3800, '26': 3800 }, new: { '25': 4085, '26': 4370 }, arnona: 285 },
                    { type: 'קרווילה מורחבת פלוס', original: { '24': 4200, '25': 4200, '26': 4200 }, new: { '25': 4515, '26': 4830 }, arnona: 315 },
                ],
                '30-37': [
                    { type: 'דירת נוער/סדנה/גדולה', original: { '24': 3400, '25': 3400, '26': 3400 }, new: { '25': 3700, '26': 4000 }, arnona: 217 },
                    { type: 'דירה מורחבת/קטנה', original: { '24': 3400, '25': 3400, '26': 3400 }, new: { '25': 3600, '26': 3800 }, arnona: 286 },
                    { type: 'קרווילה מורחבת', original: { '24': 4100, '25': 4100, '26': 4100 }, new: { '25': 4500, '26': 4900 }, arnona: 285 },
                    { type: 'קרווילה מורחבת פלוס', original: { '24': 4500, '25': 4500, '26': 4500 }, new: { '25': 4900, '26': 5300 }, arnona: 315 },
                ],
                'תושבים וגילאי 38 ומעלה': [
                    { type: 'דירת נוער/סדנה/גדולה', original: { '24': 4800, '25': 4800, '26': 4800 }, new: { '25': 5200, '26': 5600 }, arnona: 217 },
                    { type: 'דירה מורחבת/קטנה', original: { '24': 4700, '25': 4700, '26': 4700 }, new: { '25': 5100, '26': 5500 }, arnona: 286 },
                    { type: 'קרווילה מורחבת', original: { '24': 5600, '25': 5600, '26': 5600 }, new: { '25': 6100, '26': 6600 }, arnona: 285 },
                    { type: 'קרווילה מורחבת פלוס', original: { '24': 6000, '25': 6000, '26': 6000 }, new: { '25': 6500, '26': 7000 }, arnona: 315 },
                ]
            }
        };

        // --- State Management ---
        let currentChart = null;
        let currentState = {
            location: 'בקעה',
            age: 'עד גיל 30'
        };

        // --- DOM Elements ---
        const tableBody = document.getElementById('price-table-body');
        const chartTitle = document.getElementById('chart-title');
        const ctx = document.getElementById('priceChart').getContext('2d');

        // --- Functions ---

        /**
         * Calculates the average price for a given dataset and year.
         * @param {Array} data - The array of apartment data.
         * @param {String} year - The year to calculate for ('24', '25', '26').
         * @param {String} type - 'original' or 'new'.
         * @returns {Number} The average price.
         */
        function getAveragePrice(data, year, type) {
            if (!data || data.length === 0) return 0;
            const total = data.reduce((sum, item) => sum + item[type][year], 0);
            return Math.round(total / data.length);
        }
        
        /**
         * Renders the data table based on the current state.
         * @param {Array} data - The array of apartment data for the current selection.
         */
        function renderTable(data) {
            tableBody.innerHTML = '';
            if (!data || data.length === 0) {
                tableBody.innerHTML = '<tr><td colspan="5" class="text-center p-8 text-gray-500">לא נמצאו נתונים לבחירה זו.</td></tr>';
                return;
            }
            data.forEach(item => {
                const row = `
                    <tr class="hover:bg-gray-50">
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">${item.type}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-500">${item.original['24'].toLocaleString()} ₪</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-center">
                            <span class="price-original">${item.original['25'].toLocaleString()} ₪</span> / <span class="price-new">${item.new['25'].toLocaleString()} ₪</span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-center">
                            <span class="price-original">${item.original['26'].toLocaleString()} ₪</span> / <span class="price-new">${item.new['26'].toLocaleString()} ₪</span>
                        </td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-center text-gray-500">${item.arnona.toLocaleString()} ₪</td>
                    </tr>
                `;
                tableBody.innerHTML += row;
            });
        }

        /**
         * Renders the chart based on the current state.
         * @param {Array} data - The array of apartment data for the current selection.
         */
        function renderChart(data) {
            if (currentChart) {
                currentChart.destroy();
            }
            
            const labels = ['ספט\' 24', 'ספט\' 25', 'ספט\' 26'];
            
            const originalData = [
                getAveragePrice(data, '24', 'original'),
                getAveragePrice(data, '25', 'original'),
                getAveragePrice(data, '26', 'original')
            ];

            const newData = [
                getAveragePrice(data, '24', 'original'), // Starts same as original
                getAveragePrice(data, '25', 'new'),
                getAveragePrice(data, '26', 'new')
            ];

            currentChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: labels,
                    datasets: [
                        {
                            label: 'הסכם מקורי',
                            data: originalData,
                            borderColor: '#16A34A', // green-600
                            backgroundColor: 'rgba(22, 163, 74, 0.1)',
                            fill: true,
                            tension: 0.1
                        },
                        {
                            label: 'הצעה חדשה',
                            data: newData,
                            borderColor: '#DC2626', // red-600
                            backgroundColor: 'rgba(220, 38, 38, 0.1)',
                            fill: true,
                            tension: 0.1
                        }
                    ]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            position: 'top',
                            labels: {
                                font: {
                                    size: 14,
                                    family: 'Assistant, sans-serif'
                                }
                            }
                        },
                        tooltip: {
                            mode: 'index',
                            intersect: false,
                            callbacks: {
                                label: function(context) {
                                    let label = context.dataset.label || '';
                                    if (label) {
                                        label += ': ';
                                    }
                                    if (context.parsed.y !== null) {
                                        label += new Intl.NumberFormat('he-IL', { style: 'currency', currency: 'ILS', minimumFractionDigits: 0 }).format(context.parsed.y);
                                    }
                                    return label;
                                }
                            }
                        }
                    },
                    scales: {
                        y: {
                            beginAtZero: false,
                            ticks: {
                                callback: function(value, index, values) {
                                    return value.toLocaleString() + ' ₪';
                                }
                            }
                        }
                    }
                }
            });
        }

        /**
         * Main update function to refresh the UI based on the current state.
         */
        function updateUI() {
            const data = priceData[currentState.location]?.[currentState.age];
            
            // Update title
            chartTitle.textContent = `ניתוח מחירים: ${currentState.location} - ${currentState.age}`;
            
            // Render components
            renderTable(data);
            renderChart(data);

            // Update active button styles
            document.querySelectorAll('.location-btn').forEach(btn => {
                btn.classList.toggle('active', btn.dataset.location === currentState.location);
            });
            document.querySelectorAll('.age-btn').forEach(btn => {
                btn.classList.toggle('active', btn.dataset.age === currentState.age);
            });
        }

        // --- Event Listeners ---
        document.querySelector('.flex').addEventListener('click', (e) => {
            if (e.target.matches('.location-btn')) {
                currentState.location = e.target.dataset.location;
                updateUI();
            }
            if (e.target.matches('.age-btn')) {
                currentState.age = e.target.dataset.age;
                updateUI();
            }
        });

        // --- Initial Load ---
        window.addEventListener('DOMContentLoaded', () => {
             // Set default active buttons on load
            document.querySelector(`[data-location="${currentState.location}"]`).classList.add('active');
            document.querySelector(`[data-age="${currentState.age}"]`).classList.add('active');
            updateUI();
        });

    </script>
</body>
</html>
